namespace AgentTrust.Data;
public sealed class HotelBookingEntity
{ public string BookingId { get; set; } = ""; public string PrincipalId { get; set; } = ""; public string AgentId { get; set; } = ""; public string MandateId { get; set; } = ""; public string PaymentMethodId { get; set; } = ""; public string ProviderId { get; set; } = ""; public string Objective { get; set; } = ""; public string RoomId { get; set; } = ""; public DateOnly CheckIn { get; set; } public DateOnly CheckOut { get; set; } public int Guests { get; set; } public bool Accessible { get; set; } public decimal Total { get; set; } public string Currency { get; set; } = ""; public string QuoteId { get; set; } = ""; public string? ReservationId { get; set; } public string? ProviderReference { get; set; } public string? PaymentReference { get; set; } public string IdempotencyKey { get; set; } = ""; public string Status { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } public string? FailureReason { get; set; } public long Version { get; set; } }
public sealed class HotelQuoteEntity
{ public string QuoteId { get; set; } = ""; public string BookingId { get; set; } = ""; public string ProviderId { get; set; } = ""; public decimal Total { get; set; } public string Currency { get; set; } = ""; public DateTimeOffset ExpiresAt { get; set; } public string DetailsJson { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } public long Version { get; set; } }
public sealed class HotelReservationEntity
{ public string ReservationId { get; set; } = ""; public string BookingId { get; set; } = ""; public string ProviderId { get; set; } = ""; public DateTimeOffset ExpiresAt { get; set; } public string Status { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } public long Version { get; set; } }
public sealed class HotelBookingAuditEntity
{ public long Sequence { get; set; } public string EventId { get; set; } = ""; public string BookingId { get; set; } = ""; public string PrincipalId { get; set; } = ""; public string EventType { get; set; } = ""; public string PreviousHash { get; set; } = ""; public string CurrentHash { get; set; } = ""; public string DataJson { get; set; } = ""; public DateTimeOffset Timestamp { get; set; } }
