// <auto-generated />
using System;
using AgentTrust.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentTrust.Data.Migrations.Postgres.Migrations
{
    [DbContext(typeof(AgentTrustDbContext))]
    [Migration("20260903202758_MakeDelegatedAuthorityDailyLimitOptional")]
    partial class MakeDelegatedAuthorityDailyLimitOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentTrust.Data.AgentEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CredentialStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerTrustAnchor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AgentId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AgentTrust.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalIssuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.HasIndex("ExternalIssuer", "ExternalSubject")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AgentTrust.Data.ApprovalRequestEntity", b =>
                {
                    b.Property<string>("ApprovalId")
                        .HasColumnType("text");

                    b.Property<string>("Approver")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalOutcome")
                        .HasColumnType("text");

                    b.Property<string>("OriginalDecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("AgentTrust.Data.AuditRecordEntity", b =>
                {
                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("TransactionId");

                    b.ToTable("AuditRecords");
                });

            modelBuilder.Entity("AgentTrust.Data.CheckoutExecutionEntity", b =>
                {
                    b.Property<string>("CheckoutExecutionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("CheckoutExecutionId");

                    b.HasIndex("PaymentIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PurchaseIntentId")
                        .IsUnique();

                    b.ToTable("CheckoutExecutions");
                });

            modelBuilder.Entity("AgentTrust.Data.ConnectedServiceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialReference")
                        .HasColumnType("text");

                    b.Property<string>("ExternalAccountReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId", "Provider", "ExternalAccountReference")
                        .IsUnique();

                    b.ToTable("ConnectedServices");
                });

            modelBuilder.Entity("AgentTrust.Data.ConsumerPaymentAttemptEntity", b =>
                {
                    b.Property<string>("PaymentAttemptId")
                        .HasColumnType("text");

                    b.Property<string>("CheckoutExecutionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text");

                    b.Property<string>("LatestStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderPaymentMethodId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PaymentAttemptId");

                    b.HasIndex("PaymentIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.HasIndex("LatestStatus", "UpdatedAt");

                    b.ToTable("ConsumerPaymentAttempts", (string)null);
                });

            modelBuilder.Entity("AgentTrust.Data.ConsumerPaymentMethodEntity", b =>
                {
                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("integer");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("PrincipalId", "Status");

                    b.HasIndex("Provider", "ProviderToken")
                        .IsUnique();

                    b.ToTable("ConsumerPaymentMethods");
                });

            modelBuilder.Entity("AgentTrust.Data.ConsumerProfileEntity", b =>
                {
                    b.Property<string>("PrincipalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PrincipalId");

                    b.ToTable("ConsumerProfiles");
                });

            modelBuilder.Entity("AgentTrust.Data.ConsumerPurchaseTaskEntity", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandateVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MerchantScopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextExecutionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShoppingListJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TaskId");

                    b.HasIndex("NextExecutionAt");

                    b.HasIndex("PrincipalId", "Status");

                    b.ToTable("ConsumerPurchaseTasks");
                });

            modelBuilder.Entity("AgentTrust.Data.DecisionFeedbackEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("ActualOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("AgentConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("AiRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("HumanConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("InvestigationId")
                        .HasColumnType("text");

                    b.Property<string>("MisleadingEvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsefulEvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("ValidationStatus");

                    b.ToTable("DecisionFeedback");
                });

            modelBuilder.Entity("AgentTrust.Data.DelegatedAuthorityEntity", b =>
                {
                    b.Property<string>("AuthorityId")
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApprovedMerchants")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date");

                    b.Property<string>("GeographicScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HumanApprovalAbove")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PerTransactionLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("time without time zone");

                    b.HasKey("AuthorityId");

                    b.HasIndex("AgentId");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("AgentTrust.Data.EvidenceManifestEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("CitedEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredEvidenceTypesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.ToTable("EvidenceManifests");
                });

            modelBuilder.Entity("AgentTrust.Data.FinancialMandateEntity", b =>
                {
                    b.Property<string>("MandateId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("AboveLimit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DailyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PerTransactionLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupersedesMandateId")
                        .HasColumnType("text");

                    b.Property<string>("TaskParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WeeklyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("MandateId", "Version");

                    b.HasIndex("AgentId", "Status");

                    b.HasIndex("PrincipalId", "Status");

                    b.ToTable("FinancialMandates");
                });

            modelBuilder.Entity("AgentTrust.Data.InvestigationStateEntity", b =>
                {
                    b.Property<string>("InvestigationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InvestigationId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.ToTable("InvestigationStates");
                });

            modelBuilder.Entity("AgentTrust.Data.MerchantEntity", b =>
                {
                    b.Property<string>("MerchantId")
                        .HasColumnType("text");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MerchantId");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("AgentTrust.Data.OneOffAuthorisationEntity", b =>
                {
                    b.Property<string>("AuthorisationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandateVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("AuthorisationId");

                    b.HasIndex("PurchaseIntentId")
                        .IsUnique();

                    b.HasIndex("TransactionFingerprint")
                        .IsUnique();

                    b.ToTable("OneOffAuthorisations");
                });

            modelBuilder.Entity("AgentTrust.Data.PaymentOutcomeEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.ToTable("PaymentOutcomes");
                });

            modelBuilder.Entity("AgentTrust.Data.PendingConsumerApprovalEntity", b =>
                {
                    b.Property<string>("ApprovalId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ApproverSubject")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ApprovalId");

                    b.HasIndex("PurchaseIntentId")
                        .IsUnique();

                    b.HasIndex("PrincipalId", "Status");

                    b.ToTable("PendingConsumerApprovals");
                });

            modelBuilder.Entity("AgentTrust.Data.PolicyDecisionEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("ChecksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.ToTable("PolicyDecisions");
                });

            modelBuilder.Entity("AgentTrust.Data.PrincipalBindingEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BindingEvidenceRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AgentId");

                    b.ToTable("Bindings");
                });

            modelBuilder.Entity("AgentTrust.Data.PrincipalEntity", b =>
                {
                    b.Property<string>("PrincipalId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PrincipalId");

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("AgentTrust.Data.ProfileSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("ProfileSnapshots");
                });

            modelBuilder.Entity("AgentTrust.Data.PurchaseAuthorisationEntity", b =>
                {
                    b.Property<string>("AuthorisationId")
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AuthorisedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SigningKeyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("AuthorisationId");

                    b.HasIndex("PurchaseIntentId")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("PurchaseAuthorisations");
                });

            modelBuilder.Entity("AgentTrust.Data.PurchaseExecutionEntity", b =>
                {
                    b.Property<string>("ExecutionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredAction")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ExecutionId");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.HasIndex("PurchaseIntentId")
                        .IsUnique();

                    b.HasIndex("PrincipalId", "State");

                    b.HasIndex("TaskId", "ScheduledFor")
                        .IsUnique();

                    b.ToTable("PurchaseExecutions");
                });

            modelBuilder.Entity("AgentTrust.Data.PurchaseIntentEntity", b =>
                {
                    b.Property<string>("PurchaseIntentId")
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasketJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryAddressReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("QuoteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedDeliveryWindow")
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PurchaseIntentId");

                    b.HasIndex("ExecutionId")
                        .IsUnique();

                    b.HasIndex("PaymentIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PrincipalId", "CreatedAt");

                    b.ToTable("PurchaseIntents");
                });

            modelBuilder.Entity("AgentTrust.Data.PurchaseLifecycleEventEntity", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("PurchaseIntentId", "SequenceNumber");

                    b.ToTable("PurchaseLifecycleEvents");
                });

            modelBuilder.Entity("AgentTrust.Data.PurchaseReceiptEntity", b =>
                {
                    b.Property<string>("ReceiptId")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.HasIndex("PurchaseIntentId")
                        .IsUnique();

                    b.HasIndex("PrincipalId", "PurchasedAt");

                    b.ToTable("PurchaseReceipts");
                });

            modelBuilder.Entity("AgentTrust.Data.SemanticCaseEntity", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EmbeddingCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingModelVersion")
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CaseId");

                    b.HasIndex("ScopeId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SemanticCases");
                });

            modelBuilder.Entity("AgentTrust.Data.SpendReservationEntity", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FinalisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandateVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ReservationId");

                    b.HasIndex("ExecutionId")
                        .IsUnique();

                    b.HasIndex("MandateId", "Status", "ReservedAt");

                    b.ToTable("SpendReservations");
                });

            modelBuilder.Entity("AgentTrust.Data.StripeWebhookEventEntity", b =>
                {
                    b.Property<string>("ProviderEventId")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ProviderCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ProviderEventId");

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("StripeWebhookEvents");
                });

            modelBuilder.Entity("AgentTrust.Data.TaskOccurrenceEntity", b =>
                {
                    b.Property<string>("OccurrenceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("OccurrenceId");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("TaskId", "ScheduledFor")
                        .IsUnique();

                    b.ToTable("TaskOccurrences");
                });

            modelBuilder.Entity("AgentTrust.Data.TransactionEventEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("BeneficiaryCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BeneficiaryId")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorFailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasRefunded")
                        .HasColumnType("boolean");

                    b.HasKey("TransactionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MerchantId");

                    b.ToTable("TransactionEvents");
                });

            modelBuilder.Entity("AgentTrust.Data.TransactionIntentEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.ToTable("TransactionIntents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgentTrust.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
